### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Form-Robert#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen proyecto @Roberttovarv  ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- Todo genial en este proyecto... únicamente te diría que intentes dejar los márgenes laterales con el fondo negro como en la [imagen](https://storage.googleapis.com/breathecode-asset-images/b1dce6958cdd29b72248a6db2e6450994eedbaeae3f9086b5bc78a30cfa2d15c.png?raw=true) de referencia.

**Comment by EduardoHernandezGuzman** [comment]
No me hagas caso en cuanto a lo de dejar los márgenes negros  :smiley::smiley::smiley:
Es tema de la captura de pantalla.

**Comment by Roberttovarv** [comment]
Muchas gracias Edo!!!
